### ISSUE TITLE
Setup CI system

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/crypto#4]
The CI has not been setup for this repo. @dkastl I think the DCO check is missing (i don't know how you added it) and we don't have the tape tests running.

**Comment by dkastl** [comment]
Good question ... how did I add this DCO bot ...

**Comment by dkastl** [comment]
Found and added it. It's in the Github organization settings: https://github.com/organizations/consento-org/settings/installations

**Comment by dkastl** [comment]
The settings are by repository, so every repository we want to add the DCO bot needs to be enabled manually.

**Comment by martinheidegger** [comment]
@dkastl thanks!

**Comment by RangerMauve** [comment]
Tests are failing on [this line](https://github.com/consento-org/crypto/blame/master/src/primitives/__tests__/index.test.ts#L166) at the moment, but I'll set them up anyway for once it's fixed. 😁

Gonna run them on Linux to start.

**Comment by RangerMauve** [comment]
What's the DCO bot?

**Comment by RangerMauve** [comment]
For some reason the actions aren't showing up even though I added the workflow to the repo.

**Comment by dkastl** [comment]
@RangerMauve , DCO is quickly described here https://github.com/consento-org/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin-dco and is supposed to handle https://developercertificate.org/ . Martin and I thought it's the better alternative to CLA's. We didn't setup the bot on all repositories, because we forgot to do so ;-)

It's quite easy to setup locally, so you won't be asked anymore. Which is also the reason, why we forgot, that some new repositories don't check it ;-)

**Comment by RangerMauve** [comment]
@martinheidegger I don't think I have permission to enable actions on this repo. Do you think you'll have a chance to either grant them to me or to enable it? 😁

**Comment by martinheidegger** [comment]
I didn't notice that you don't have permission, enabled permissions for you on this and other repos (manual process?!)

**Comment by martinheidegger** [comment]
Fixed with 9582c40e6989d184201fb30927c4b2988f7a03df
